location ~* ^/(manifest\.json|sw\.js|icon-[0-9]+\.png|apple-touch-icon\.png|favicon\.ico|favicon-[0-9]+x[0-9]+\.png)$ {
    auth_basic off;
    proxy_pass http://sito-reckeweg:33000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    add_header Cache-Control "no-cache";
}